services:
  server:
    build:
      context: .
    volumes:
       - db_data_sqlite:/var/lib/kutt
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
    ports:
      - 3000:3000
volumes:
  db_data_sqlite: